In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
titles = pd.read_excel("emp_titles.xlsx")

In [3]:
titles["emp_title"] = (titles["emp_title"]
                       .str.lower()
                       .str.replace("(","").str.replace(")","")
                       .str.replace(" 0 ","").str.replace(" 1 ","")
                       .str.replace(" 2 ","").str.replace(" 3 ","")
                       .str.replace(" 4 ","").str.replace(" 5 ","")
                       .str.replace(" 6 ","").str.replace(" 7 ","")
                       .str.replace(" 8 ","").str.replace(" 9 ","")
                       .str.replace('"',"").str.replace("'","")
                       .str.replace("V","").str.replace("I","")
                       .str.replace("lll","").str.replace("iii","")
                       .str.replace(" iv ","").str.replace("â€‹","")
                       .str.strip())

In [4]:
titles.value_counts()

emp_title
teacher                    10241
manager                     9325
owner                       6190
registered nurse            4660
supervisor                  4515
                           ...
fte, specialist                1
fte analyst                    1
ftc                            1
ftbs direct worker             1
zsenior project manager        1
Name: count, Length: 95683, dtype: int64

In [158]:
freq_titles = pd.read_csv("emp_words.tsv",sep="\t")

In [159]:
freq_titles.columns = ["word", "count"]

In [160]:
freq_titles.loc[freq_titles.word == "nurse","count"] += freq_titles[freq_titles.word == "rn"]["count"].item()
freq_titles.loc[freq_titles.word == "rn","count"] = 0

freq_titles.loc[freq_titles.word == "technician","count"] += (
    freq_titles[freq_titles.word == "tech"]["count"].item()
    +
    freq_titles[freq_titles.word == "technical"]["count"].item()
    )
freq_titles.loc[freq_titles.word == "tech","count"] = 0
freq_titles.loc[freq_titles.word == "technical","count"] = 0

freq_titles.loc[freq_titles.word == "administrator","count"] += (
    freq_titles[freq_titles.word == "admin"]["count"].item()
    +
    freq_titles[freq_titles.word == "administrative"]["count"].item()
    )
freq_titles.loc[freq_titles.word == "admin","count"] = 0
freq_titles.loc[freq_titles.word == "administrative","count"] = 0

freq_titles.loc[freq_titles.word == "account","count"] += (
    freq_titles[freq_titles.word == "accountant"]["count"].item()
    +
    freq_titles[freq_titles.word == "accounting"]["count"].item()
    )
freq_titles.loc[freq_titles.word == "accountant","count"] = 0
freq_titles.loc[freq_titles.word == "accounting","count"] = 0

freq_titles.loc[freq_titles.word == "service","count"] += freq_titles[freq_titles.word == "services"]["count"].item()
freq_titles.loc[freq_titles.word == "services","count"] = 0

freq_titles.loc[freq_titles.word == "manager","count"] += freq_titles[freq_titles.word == "mgr"]["count"].item()
freq_titles.loc[freq_titles.word == "mgr","count"] = 0

mgr - manager
vp - vice president
pr - Practice

In [161]:
freq_titles.nlargest(40,"count")

                word  count
13969        manager  64151
23748     technician  16781
7559        director  15827
20718          sales  14883
2521       assistant  14874
15818          nurse  13523
23495        teacher  11881
22976     supervisor  11850
22122     specialist  11607
8903        engineer  11596
1902         analyst  11555
21449        service  11387
21313         senior  11384
973          account   9543
8048          driver   9150
16070        officer   8692
1351   administrator   8521
16001             of   8410
16737          owner   6866
6090     coordinator   6651
16307     operations   6352
18775        project   5974
16364       operator   5763
2654       associate   5711
19757     registered   5398
18255      president   5291
16030         office   5203
9403       executive   4916
12963           lead   4841
3964        business   4691
5802      consultant   4656
12448             it   4117
22366            sr.   4077
10546        general   3920
6784        customer   3740
5044           clerk   3516
23147        support   3424
25011           vice   3393
18707        program   3210
2008             and   2923

In [131]:
freq_titles = freq_titles[~freq_titles["word"].isin(["of","operations","senior",
                                                     "project",'it','sr.','lead',
                                                     'registered','office','vice',
                                                     'support','general','customer',
                                                     'program','and','financial','human',
                                                     'sr','truck','software','hr',
                                                     'production','medical','management',
                                                     'rep','development','quality','store','&',
                                                     'vp','ii','field','team','regional',
                                                     'clinical','branch','finance','warehouse',
                                                     'network','care','loan','legal'])]

In [133]:
words_dictionary = dict(sorted(freq_titles.set_index("word").nlargest(50,"count").squeeze().to_dict().items(), key=lambda x:x[1], reverse=True))

In [138]:
count = 0
for x in words_dictionary.keys():
    words_dictionary[x] = count
    count+=1

In [139]:
words_dictionary

{'manager': 0,
 'technician': 1,
 'director': 2,
 'sales': 3,
 'assistant': 4,
 'nurse': 5,
 'teacher': 6,
 'supervisor': 7,
 'specialist': 8,
 'engineer': 9,
 'analyst': 10,
 'service': 11,
 'account': 12,
 'driver': 13,
 'officer': 14,
 'administrator': 15,
 'owner': 16,
 'coordinator': 17,
 'operator': 18,
 'associate': 19,
 'president': 20,
 'executive': 21,
 'business': 22,
 'consultant': 23,
 'clerk': 24,
 'maintenance': 25,
 'systems': 26,
 'marketing': 27,
 'mechanic': 28,
 'representative': 29,
 'security': 30,
 'agent': 31,
 'police': 32,
 'attorney': 33,
 'worker': 34,
 'therapist': 35,
 'staff': 36,
 'chief': 37,
 'principal': 38,
 'advisor': 39,
 'leader': 40,
 'foreman': 41,
 'developer': 42,
 'designer': 43,
 'secretary': 44,
 'professor': 45,
 'controller': 46,
 'server': 47,
 'banker': 48,
 'deputy': 49}

In [140]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

# Your list of employee titles
employee_titles = titles["emp_title"].to_list()

In [145]:
# calculate the most frequent features first
vect = TfidfVectorizer(vocabulary=words_dictionary, max_features=100)
matrix = vect.fit_transform(employee_titles)
top_features = vect.vocabulary_
n = len(top_features)

for feature, index in words_dictionary.items():
    top_features[feature] = index

# re-vectorize using both sets of features
# at this point len(top_features) == 13
vect = TfidfVectorizer(vocabulary=top_features)
X = vect.fit_transform(employee_titles)

In [155]:
# OPTIONAL
# Transform titles into TF-IDF features
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(employee_titles)

In [146]:
len(employee_titles)

395318

In [148]:
# Apply KMeans clustering
kmeans = KMeans(n_clusters=38, random_state=42, n_init = 'auto')
kmeans.fit(X)

# Get cluster labels
labels = kmeans.labels_

# Create clusters dictionary
clusters = {}
for i, title in enumerate(employee_titles):
    cluster_label = labels[i]
    if cluster_label not in clusters:
        clusters[cluster_label] = []
    clusters[cluster_label].append(title)

# Print the clusters
for cluster_label, cluster_titles in dict(sorted(clusters.items())).items():
    print(f"Cluster {cluster_label}:")
    print(cluster_titles[0:20])
    print("\n")

Cluster 0:
['day care proivder', 'letter carrier', 'carpenter', 'lead caterer', 'adv mtr proj fld rep', 'ac tech', 'admin asst', 'advance cnn', 'aftermarket expeditor', 'apprentice', 'architect', 'area leader', 'assembler', 'assembler', 'auditor', 'avp, private client support', 'baker', 'banker', 'barber', 'bi reports developer']


Cluster 1:
['assistant store manager', 'administration assistant', 'assistant branch manager', 'assistant butler', 'assistant manager', 'assistant principal', 'assistant store manager', 'assistant store manager in training', 'lab assistant', 'medical assistant', 'nursing assistant', 'ocuppational therapy assistant', 'school age care assistant', '!st assistant plumbing manager', '1950 assistant purchaser', '1st assistant', '1st assistant accountant', '1st assistant camera', '1st assistant d a', '1st assistant director']


Cluster 2:
['electronics manager', 'acc manager', 'accounting  manager', 'collection manager', 'cyber project manager', 'department manager', 'dept manager', 'division frontend manager', 'facilities manager', 'food safety & quality manager', 'general manager', 'grocery manager', 'inventory manager', 'kitchen manager', 'licensed relationship manager', 'manager', 'manager', 'manager', 'manager', 'manager']


Cluster 3:
['behavior specialist', 'card services specialist', 'child protective specialist', 'compliance specialist', 'distribution specialist', 'employment specialist', 'itoperations specialist', 'legal office specialist', 'medical credentialing specialist', 'office specialist', '10b5 specialist', '2101 airway specialist lvl ii', '2210 it specialist', '2210- it specialist', '401k specialist', '92g food operation specialist', 'a.p.a., document specialist', 'a/dacg specialist', 'a/p & garnishment specialist', 'a/p specialist']


Cluster 4:
['co-owner', 'owner/photographer', '100% full owner', '49% owner', 'a member, owner', 'accountant - owner', 'accountant/owner', 'acupuncturist/owner', 'admiin/owner', 'advisor/owner', 'agency owner', 'agency owner', 'agency owner', 'agency owner', 'agency owner', 'agency owner', 'agency owner', 'agency owner', 'agency owner', 'agency owner']


Cluster 5:
['derivative analyst', 'financial analyst', 'financial analyst', 'senior supply analyst', 'sr. analyst', '2 level it analyst', 'a/p analyst', 'a/r analyst', 'a/r analyst', 'a/r analyst', 'a/r analyst', 'a/r analyst', 'a/r portfolio analyst', 'academic program analyst', 'access administration analyst', 'access control analyst', 'accountable property analyst', 'accountant analyst', 'accountant analyst', 'accountant analyst']


Cluster 6:
['director', 'and planned director of major gifts', 'assitant director', 'asst. director of support services', 'asst. site director', 'buisness development director- spa', 'director of institutional research', 'director of operations', 'director of production and development', 'it director', 'project director', '911 director', '911 director', 'academic director', 'academic director', 'academic services director', 'academic services director', 'academy director', 'academy director', 'academy director/principal']


Cluster 7:
['driver / supervisor', 'driver supervisor', 'driver supervisor', 'driver supervisor', 'driver supervisor', 'driver supervisor', 'driver supervisor', 'driver supervisor', 'driver supervisor', 'driver supervisor', 'driver/ driver supervisor', 'driver/ supervisor', 'driver/supervisor', 'driver/supervisor', 'driver/supervisor', 'driver/supervisor', 'driver/supervisor', 'lead driver/supervisor', 'pile driver supervisor', 'shop supervisor truck driver']


Cluster 8:
['estimator and sales rep', 'factor sales rep', 'inside sales', 'sales', 'sales', 'sales', 'sales', 'sales', 'sales', 'sales manager', '1099 employee- sales manager', 'a&d sales manager', 'a.v.p sales', 'accounting/sales', 'accounts payable/sales', 'accounts receivable/sales tax manager', 'acoustic sales manager', 'ad sales director', 'admin and sales operation manager', 'admin. asst. sales']


Cluster 9:
['afjrotc teacher', 'assistant teacher', 'librarian/teacher', 'teacher', 'teacher', 'teacher', 'teacher', 'teacher', 'teacher assistant', '1st grade teacher', '1st grade teacher', '1st grade teacher', '1st grade teacher', '1st grade teacher', '1st grade teacher', '1st grade teacher', '1st grade teacher', '1st grade teacher', '1st grade teacher', '1st grade teacher']


Cluster 10:
['building engineer', '1st engineer', '2 nd engineer', '2nd assistant engineer', '2nd assistant engineer pipeline', '2nd engineer', '2nd engineer', '3d cad computer engineer', '3rd assistant marine engineer', '911 engineer', 'a/v engineer', 'access management engineer', 'acd engineer', 'acoustic engineer', 'active directory engineer', 'active directory migration engineer', 'advance manufacturing engineer', 'advance supplier quality engineer', 'advanced devops automation engineer', 'advanced field engineer']


Cluster 11:
['ambulatory rn clinic supervisor', 'job site supervisor', 'kitchen supervisor', 'lab supervisor', 'military pay supervisor', 'or supervisor', 'payroll supervisor', 'qa supervisor', 'satellite supervisor', 'stock supervisor', 'supervisor', 'supervisor', 'supervisor', 'supervisor', 'supervisor of transportation operations', 'team leader supervisor', '1st mortgage supervisor', '1st shift supervisor', '204b supervisor', '21 supervisor']


Cluster 12:
['automotive technician', 'bus technician', 'certified pharmacy technician', 'field service technician', 'instrument and control technician', 'office technician', 'technician', 'technician', 'train technician', '3rd shift lead technician', '911 technician', 'a & p technician', 'a technician', 'a&p sr technician', 'a&p technician', 'a&t technician', 'a/c & refrigeration technician', 'a/c technician', 'a/c technician', 'a/c technician']


Cluster 13:
['licensed practical nurse', 'nurse practitioner', 'registered nurse', 'registered nurse', 'registered nurse', 'registered nurse', 'registered nurse', 'school nurse', 'access nurse', 'accreditation specialist - nurse lead', 'acting nurse manager', 'acute care nurse manager', 'acute care nurse practitioner', 'administrative  nurse', 'administrative nurse', 'administrative public health nurse', 'administrative registered nurse', 'admission nurse', 'admission nurse', 'admission nurse']


Cluster 14:
['compliance officer', 'l corrections officer', 'loan officer', 'loan officer', 'peace officer', '0-6 col comm officer', '1st class petty officer', '2nd class petty officer', '911 training officer', 'aa/eeo compliance officer', 'ac officer', 'access officer', 'account security officer', 'accounting officer', 'accounting officer', 'accounting officer', 'accounting officer', 'accounting officer', 'accounting officer', 'accounting officer specialist']


Cluster 15:
['copy clerk', 'inventory clerk', 'shipping receiving clerk', '10th circuit court records clerk', '1408-principal clerk', '1426 sr. clerk typist', '2nd settlement clerk/corporate trainer', 'a/p clerk', 'a/p clerk', 'a/r - a/p clerk', 'a/r clerk', 'a/r clerk', 'a/r clerk', 'a/r clerk', 'a/r clerk', 'a/r clerk', 'a/r clerk', 'a/r clerk', 'a/r clerk', 'a/r clerk']


Cluster 16:
['executive and marketing coordinator', 'executive assistant/coordinator', 'executive assistant/coordinator', 'executive coordinator', 'executive coordinator', 'executive coordinator', 'executive coordinator', 'executive coordinator', 'executive coordinator', 'executive coordinator', 'executive coordinator', 'executive coordinator', 'executive coordinator', 'executive coordinator', 'executive coordinator', 'executive coordinator', 'executive coordinator', 'executive coordinator', 'executive relations coordinator', 'executive/coordinator']


Cluster 17:
['commercial driver', 'driver', 'driver', 'driver', 'driver', 'driver', 'driver', 'driver / labour', 'fork truck driver', 'team leader / driver examiner', 'truck driver', 'truck driver', 'truck driver', 'truck driver', 'truck driver', 'cdl bus driver', '1. lpn/ 2. driver', '1st seat driver', 'ace delivery driver', 'agg truck driver']


Cluster 18:
['elevator clearance operator', 'driver/ operator', 'equipment operator', 'forklift operator', 'machine operator', 'machine operator', 'machine operator', 'machine operator', 'machine operator', 'napkin operator', 'operator', 'owner operator', 'plant operator', 'press operator', 'reverse unit operator', 'c operator', '#1press operator', '#2process operator', '1 st operator', '17ft bulldozer operator']


Cluster 19:
['dining service', 'public service supervisor', 'service deli', 'service provider', 'a/c service tech', 'access service rep', 'accessioning/client service', 'accounts payable customer service', 'acting customer service supervisor', 'admin assist/customer service', 'admin. service assistant', 'admin/customer service', 'administrative service manager', 'adminstrative service assist', 'adult day service faclitator', 'adult protective service', 'adult service specialist', 'advanced service tech', 'after sales customer service', 'aftermarket sales and service']


Cluster 20:
['capital account manager', 'physician account rep and data entry', 'academic account manager', 'account', 'account', 'account', 'account', 'account', 'account', 'account', 'account', 'account', 'account', 'account  payable', 'account  supervisor', 'account & development coordinator', 'account aanager', 'account accounts recievables', 'account admin', 'account admin']


Cluster 21:
['civ distribution process worker', 'eligibility worker', 'sprayline worker', 'utility worker', 'acute care medical social worker', 'admitting worker', 'adoption social worker', 'adoption social worker', 'adoption social worker', 'adoptions worker', 'adult protection community worker', 'adult protective community worker ii', 'agricultural worker', 'aircraft worker', 'aircraft worker', 'aircraft worker', 'aircraft worker', 'aircraft worker', 'aircraft worker machinist', 'airport ramp worker']


Cluster 22:
['correctional services administrator', 'engineering administrator', 'subcontract administrator', 'wing administrator', '401k administrator', '61823mandatory arbitration administrator', 'a/p & a/r administrator', 'a/p administrator', 'a/r and a/p administrator', 'academic administrator', 'academic administrator', 'academic administrator', 'academic administrator', 'access aurora administrator', 'account administrator', 'account administrator', 'account administrator', 'account administrator', 'account administrator', 'account administrator']


Cluster 23:
['business analyst', 'vp business development', '1130 business center dr,', '2nd vice president new business operatio', 'about business controls manager', 'accountant/business manager', 'accounting & business application spec.', 'accounting/mgr. of business service', 'accounts payable business associate', 'ach business analysis manager', 'admin assistant/business manager', 'admin secretary to business admin', 'admissions / business office manager', 'advanced business analyst', 'advisor business process outsourcing', 'ag and business banker', 'aml business liaison', 'analyst - business management', 'analyst - business operations', 'analyst; business controls support mgr']


Cluster 24:
['3rd key sales associate', '401k plan sales associate', '529 senior associate', '529 senior associate', 'a/p associate', 'a/p associate 3', 'ab associate', 'academic associate', 'academic department associate', 'acccounting associate', 'accountant associate', 'accountant associate', 'accountant associate', 'accountant/associate', 'accounting associate', 'accounting associate', 'accounting associate', 'accounting associate', 'accounting associate', 'accounting associate']


Cluster 25:
['administrative attorney', 'advance nurse practitioner/attorney', 'agency attorney', 'agency attorney', 'agency attorney', 'agency attorney', 'appellate court attorney', 'appellate court attorney', 'assisstant attorney general', 'assistant attorney', 'assistant attorney general', 'assistant attorney general', 'assistant attorney general', 'assistant attorney general', 'assistant attorney general', 'assistant attorney general', 'assistant attorney general', 'assistant attorney general', 'assistant attorney general', 'assistant attorney general']


Cluster 26:
['consultant', 'consultant', 'leasing & sales consultant', '401k education consultant', 'aba consultant/bcba', 'academic consultant', 'account consultant', 'account consultant', 'account consultant', 'account consultant', 'account consultant', 'account consultant', 'account consultant', 'account consultant', 'account service consultant', 'account support consultant', 'accountant/consultant', 'accounting and hr consultant', 'accounting consultant', 'accounting consultant']


Cluster 27:
['agent staff', 'chat agent', 'immigration enforcement agent', 'special agent', '2nd tech support agent', '4h extension agent', 'accountant/enrolled agent', 'accounting agent', 'admin & showing agent', 'advanced repair agent', 'advanced repair agent', 'advanced repair agent', 'advanced repair agent', 'advanced repair agent', 'advanced repair agent', 'advanced repair double agent', 'agency manager-agent', 'agent', 'agent', 'agent']


Cluster 28:
['assistant vice president', 'bice president fixed income sales', 'president', 'vice president', 'vice president of sales', 'vice president relationship manager', '1st vice president', '1st vice president', '1st vice president', '1st vice president, advisory consult', '1st vice president/financial operations', 'a. vice president', 'advisor to the president', 'agency vice president', 'aide to president', 'analyst-assistant vice president', 'area manager assistant vice president', 'area vice president', 'area vice president', 'area vice president']


Cluster 29:
['appraisal coordinator', 'coordinator', 'coordinator', 'rental coordinator', '340-b coordinator', '911 addressing coordinator/gis mgr', 'a.t coordinator', 'a/p a/r coordinator', 'a/p coordinator', 'a/p coordinator', 'a/p variance coordinator', 'a/r medical records coordinator', 'academic advising coordinator', 'academic affairs coordinator', 'academic coordinator', 'academic coordinator', 'academic coordinator', 'academic coordinator', 'academic coordinator', 'academic coordinator']


Cluster 30:
['chief of police', '31b military police', '911 police communications operator', '911/police dispatcher', '911/police dispatcher', 'acting - transit police chief', 'admin. asst. police department', 'admin. police', 'assistant cheiff of police', 'assistant chief of police', 'assistant chief of police', 'assistant chief of police', 'assistant chief of police', 'assistant police chief', 'assistant to chief of police', 'asst chief of police', 'asst police chief', 'asst. police chief', 'boston school police officer', 'campus police']


Cluster 31:
['area maintenance manager', 'building maintenance tech', 'fac maintenance', 'golf maintenance', 'maintenance', 'maintenance', 'maintenance', 'maintenance-  fabricator', 'maintenance lead', 'maintenance painter', 'maintenance technician', 'night time supervisor maintenance', '2 in charge of property maintenance', '339 maintenance', 'ac maintenance', 'account maintenance', 'account maintenance coordinator', 'afm-aviation field maintenance rasm', 'age maintenance', 'agm of maintenance']


Cluster 32:
['speech-language therapist', 'aba tech or behavior therapist', 'aba therapist', 'aba therapist', 'activity therapist', 'acupuncture physcian, massage therapist,', 'addiction therapist', 'addiction therapist', 'addictions therapist', 'administrator/speech therapist', 'adult op therapist', 'adult therapist/counselor', 'advanced clinician physical therapist', 'allied therapist', 'art therapist', 'art therapist', 'art therapist', 'asst clinic director/physical therapist', 'behavior therapist', 'behavior therapist']


Cluster 33:
['auto mechanic', 'field mechanic', 'mechanic', 'mechanic', '`owner/mechanic', '787 mechanic', 'a & p mechanic', 'a maintenance mechanic', 'a mechanic', 'a mechanic', 'a&p aircraft mechanic', 'a&p mechanic', 'a&p mechanic', 'a&p mechanic', 'a&p mechanic', 'a&p mechanic', 'a&p mechanic', 'a&p mechanic', 'a&p mechanic', 'a&p mechanic']


Cluster 34:
['customer service representative', 'membership representative', 'sales representative', 'sales representative', 'a&d representative', 'a/p representative', 'a/r field representative', 'a/r representative', 'access care representative', 'access point support representative', 'access representative', 'access representative ii', 'account claims representative ii', 'account development representative', 'account development representative', 'account payables representative', 'account representative', 'account representative', 'account representative', 'account representative']


Cluster 35:
['event marketing manager', 'marketing manager', 'regional marketing coordinator', 'academic marketing', 'accounts manager / marketing', 'activity/marketing director', 'ad marketing', 'ad marketing', 'ad sales marketing manager', 'admin marketing assistant', 'admin. coordinator marketing dept', 'administrative & marketing asst', 'administrative & marketing asst', 'administrative assistant, marketing', 'administrative assistant/ marketing', 'admissions director/ marketing', 'admissions/marketing director', 'aftermarket marketing pricing', 'aftersales marketing', 'agricultural marketing specialist']


Cluster 36:
['executive assistant of sales', 'accounts executive', 'accounts executive', 'accoutn executive', 'acct executive', 'acct executive', 'acct executive', 'acct executive', 'acoount executive', 'acting chief executive officer', 'administrative executive', 'administrative executive', 'administrative executive assistant', 'administrative secretary/executive', 'advertising executive', 'advertising executive', 'agent and executive assistant', 'alliance executive', 'area executive', 'area executive/area vice president']


Cluster 37:
['associate professor', 'academic counselor / professor', 'adj assistant professor', 'adjuct professor', 'adjunct assistant professor', 'adjunct assistant professor', 'adjunct assistant professor', 'adjunct assistant professor', 'adjunct assistant professor, psychology', 'adjunct associate professor', 'adjunct asst professor', 'adjunct professor', 'adjunct professor', 'adjunct professor', 'adjunct professor', 'adjunct professor', 'adjunct professor', 'adjunct professor', 'adjunct professor', 'adjunct professor']

In [149]:
for cluster_label, cluster_titles in dict(sorted(clusters.items())).items():
    print(f"Cluster {cluster_label}:")
    print(len(cluster_titles))

Cluster 0:
134512
Cluster 1:
11829
Cluster 2:
51129
Cluster 3:
10816
Cluster 4:
7372
Cluster 5:
10030
Cluster 6:
13072
Cluster 7:
26
Cluster 8:
11110
Cluster 9:
12154
Cluster 10:
11312
Cluster 11:
11106
Cluster 12:
7881
Cluster 13:
8889
Cluster 14:
6864
Cluster 15:
3588
Cluster 16:
23
Cluster 17:
9289
Cluster 18:
6132
Cluster 19:
6508
Cluster 20:
4120
Cluster 21:
2163
Cluster 22:
3931
Cluster 23:
4424
Cluster 24:
5132
Cluster 25:
2259
Cluster 26:
4669
Cluster 27:
2515
Cluster 28:
5625
Cluster 29:
6433
Cluster 30:
2354
Cluster 31:
2661
Cluster 32:
2158
Cluster 33:
2680
Cluster 34:
2487
Cluster 35:
2743
Cluster 36:
3736
Cluster 37:
1586

In [157]:
print(clusters[13])

['licensed practical nurse', 'nurse practitioner', 'registered nurse', 'registered nurse', 'registered nurse', 'registered nurse', 'registered nurse', 'school nurse', 'access nurse', 'accreditation specialist - nurse lead', 'acting nurse manager', 'acute care nurse manager', 'acute care nurse practitioner', 'administrative  nurse', 'administrative nurse', 'administrative public health nurse', 'administrative registered nurse', 'admission nurse', 'admission nurse', 'admission nurse', 'admission nurse', 'admission nurse', 'admissions nurse', 'admissions nurse', 'admissions registered nurse', 'adult nurse practitioner', 'advance practice registered nurse', 'advance registered nurse', 'advanced practice nurse', 'advanced practice nurse', 'advanced practice nurse', 'advanced practice nurse', 'advanced practice nurse', 'advanced practice nurse', 'advanced practice nurse', 'advanced practice nurse', 'advanced practice nurse', 'advanced practice nurse', 'advanced practice nurse', 'advanced practice nurse-nurse practition', 'advanced registered nurse practitioner', 'advanced registered nurse practitioner', 'advanced registered nurse practitioner', 'advice nurse', 'army nurse', 'army nurse', 'assist nurse manager', 'assistant head nurse', 'assistant head nurse', 'assistant nurse', 'assistant nurse', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager', 'assistant nurse manager/rn', 'assistant nurse manager-rn', 'assistant nurse mgr rn', 'assistant ob nurse manager', 'assitant head nurse', 'asst chief nurse', 'asst clinical nurse manaer', 'asst nurse clinical manager', 'asst nurse manager', 'asst nurse manager', 'asst nurse manager', 'asst nurse managet', 'asst. nurse manager', 'asst. nurse manager', 'bos -rn nurse', 'call nurse lpn', 'cardiac device nurse', 'cardiology nurse practitioner', 'care coordination nurse manager', 'care giver nurse assistance', 'cart nurse', 'case manager / mmq nurse', 'case manager registered nurse', 'case manager/registered nurse', 'case nurse manager', 'cdi/ nurse', 'cerified nurse', 'certified anesthesia nurse', 'certified nurse', 'certified nurse aid', 'certified nurse aid', 'certified nurse aid', 'certified nurse aid', 'certified nurse aide', 'certified nurse aide', 'certified nurse aide', 'certified nurse aide', 'certified nurse aide', 'certified nurse aide', 'certified nurse aide', 'certified nurse aide', 'certified nurse aide', 'certified nurse aide cna', 'certified nurse anesthestist', 'certified nurse anesthetist', 'certified nurse assistance', 'certified nurse assistance', 'certified nurse assistance', 'certified nurse assistance', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assistant', 'certified nurse assit', 'certified nurse asst.', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse midwife', 'certified nurse practitioner', 'certified nurse practitioner', 'certified nurse-midwife', 'certified reg nurse first assistant', 'certified register nurse anesthetist', 'certified registered nurse anesthestist', 'certified registered nurse anesthetist', 'certified registered nurse anesthetist', 'certified registered nurse anesthetist', 'certified registered nurse anesthetist', 'certified registered nurse anesthetist', 'certified registered nurse anesthetist', 'certified registered nurse anesthetist', 'certified registered nurse anesthetist', 'certified registered nurse anesthetist', 'certified registered nurse anesthetist', 'certified registered nurse anesthetist', 'certified registered nurse anesthetist', 'certified registered nurse anesthetist', 'certified registered nurse first assista', 'certified school nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse', 'charge nurse lpn', 'charge nurse 3', 'charge nurse for a team of nurses', 'charge nurse icu', 'charge nurse , registered nurse', 'charge nurse lpn', 'charge nurse lvn', 'charge nurse rn', 'charge nurse rn', 'charge nurse rn', 'charge nurse rn', 'charge nurse rn', 'charge nurse rn', 'charge nurse unit 2f', 'charge nurse, lpn', 'charge nurse, r.n.', 'charge nurse/registered nurse', 'charge register nurse', 'charge registered nurse', 'charge registered nurse', 'charge registered nurse', 'charge registered nurse', 'charge registered nurse', 'charge/staff nurse', 'chef nurse', 'chief nurse anestetist', 'civilian army public health nurse', 'clinic manager, registered nurse', 'clinic nurse', 'clinic nurse', 'clinic nurse', 'clinic nurse', 'clinic nurse', 'clinic nurse', 'clinic nurse manager', 'clinic nurse manager', 'clinic nurse manager', 'clinical  nurse mangers', 'clinical care nurse, rn bsn', 'clinical corporate nurse', 'clinical informatics nurse', 'clinical intake nurse', 'clinical leader, nurse practitioner', 'clinical manager registered nurse', 'clinical manager, nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse 1', 'clinical nurse 2', 'clinical nurse 3', 'clinical nurse c', 'clinical nurse case manager', 'clinical nurse educater', 'clinical nurse educator', 'clinical nurse educator', 'clinical nurse educator', 'clinical nurse educator', 'clinical nurse educator', 'clinical nurse educator', 'clinical nurse educator', 'clinical nurse educator', 'clinical nurse educator', 'clinical nurse educator', 'clinical nurse educator', 'clinical nurse educator', 'clinical nurse educator', 'clinical nurse educator', 'clinical nurse guide', 'clinical nurse i', 'clinical nurse i', 'clinical nurse ii', 'clinical nurse ii', 'clinical nurse ii', 'clinical nurse ii', 'clinical nurse ii', 'clinical nurse ii', 'clinical nurse ii', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse', 'clinical nurse informatics', 'clinical nurse iv', 'clinical nurse leader', 'clinical nurse leader', 'clinical nurse liaison', 'clinical nurse liason', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse manager', 'clinical nurse resident', 'clinical nurse reviewer', 'clinical nurse specialisrt', 'clinical nurse specialist', 'clinical nurse specialist', 'clinical nurse specialist', 'clinical nurse specialist', 'clinical nurse specialist', 'clinical nurse specialist', 'clinical nurse specialist', 'clinical nurse specialist', 'clinical nurse specialist', 'clinical nurse specialist', 'clinical nurse specialist', 'clinical nurse specialist', 'clinical nurse specialist ii', 'clinical nurse superviser', 'clinical nurse supervisor', 'clinical nurse supervisor/er manager', 'clinical nurse-operating room rn', 'clinical professional nurse', 'clinical registered nurse', 'clinical registered nurse advocate', 'clinical research nurse', 'clinical resourse nurse', 'clinical staff nurse', 'clinical supervisor - registered nurse', 'cluster nurse manager', 'cna/nurse tech', 'collegiate nurse', 'community health nurse', 'community health nurse', 'community health registered nurse', 'community mental health nurse', 'complex bill review nurse', 'concurrent review nurse rn', 'continuous care nurse', 'corporate nurse', 'correctional health nurse i', 'correctional nurse- dalhart prison', 'correctional nurse ii', 'correctional psych registered nurse', 'correctional staff nurse', 'corrections nurse 2', 'corrections nurse ii', 'cosmetic  nurse', 'cpt nurse', 'critical care nurse', 'critical care nurse director', 'critical care registered nurse', 'critical care registered nurse', 'critical care senior staff nurse', 'critical care transport registered nurse', 'crna nurse anesthetist', 'cvicu nurse', 'department head, registered nurse', 'diabetes education nurse', 'diabetes nurse educator', 'dialysis nurse', 'dialysis nurse', 'direct care nurse', 'director - registered nurse', 'director od staff development nurse', 'director of nurse', 'dispensing nurse', 'district nurse', 'district nurse', 'district nurse manager', 'doctorate nurse practitioner', 'ed nurse manager', 'ed tech becoming ed nurse 8/3/2015', 'emergency department nurse manage', 'emergency dept nurse manager', 'emergency registered nurse/ charge nurse', 'emergency room charge nurse', 'emergency room nurse', 'emergency room nurse', 'emergency room nurse', 'emergency room registered nurse', 'emergency room registered nurse', 'emergency room travel registered nurse', 'enrollment nurse', 'epidemiology nurse', 'er charge nurse', 'er nurse', 'er nurse', 'er nurse', 'er nurse', 'er nurse', 'er nurse', 'er nurse practitioner', 'er nurse practitioner', 'er registered nurse', 'facility safety registered nurse', 'family nurse pracittioner', 'family nurse practioner', 'family nurse practioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'family nurse practitioner', 'field nurse', 'field nurse', 'field nurse', 'field nurse', 'field nurse', 'field nurse', 'field nurse case manager', 'field staff registered nurse', 'flight nurse', 'flight nurse', 'flight nurse', 'flight nurse', 'flight nurse', 'flight nurse', 'flight nurse', 'flight nurse', 'flight nurse', 'flight nurse', 'flight nurse', 'flight rn nurse', 'floor charge nurse', 'floor nurse', 'full time nurse', 'full time registered nurse', 'full time registered nurse', 'full time registered nurse', 'full time staff nurse', 'gi nurse', 'graduate nurse', 'graduate nurse', 'gs 11 public health nurse', 'head nurse', 'head nurse', 'head nurse', 'head nurse', 'health facilities evaluation nurse', 'health facilities evaluator nurse', 'health facilities surveillance nurse /rn', 'health facility evaluator nurse', 'home care nurse', 'home health nurse', 'home health nurse', 'home health nurse', 'home health nurse', 'home health nurse', 'homecare nurse', 'homecare nurse lpn', 'hospice resource nurse', 'hospital nurse manager', 'hospitalist nurse practitioner', 'house charge nurse', 'house staff registered nurse', 'housewide clinical nurse educator', 'icu nurse', 'icu nurse', 'icu nurse', 'icu nurse', 'icu nurse manager', 'icu nurse practitioner', 'icu register nurse', 'icu registered nurse', 'icu registered nurse', 'icu rn/charge nurse', 'icu staff nurse', 'ihome health nurse', 'infection  control nurse', 'infection co trol nurse', 'infection control nurse', 'infection control nurse supervisor', 'infection preventionist nurse', 'infectious disease nurse', 'infusion nurse', 'infusion nurse', 'infusion nurse', 'inpatient charge nurse', 'inpt. nurse', 'intake nurse', 'intake nurse', 'intake nurse', 'intensive care unit nurse', 'it nurse', 'jail nurse', 'junior public health nurse', 'l & d nurse supervison', 'labor and delivery registered nurse', 'lactation nurse', 'lead lift team/certified nurse assistant', 'lead nurse', 'lead school nurse', 'legal nurse', 'legal nurse for risk management dept', 'licence vocational nurse', 'licenced pratical nurse', 'licenced vacational nurse', 'license nurse', 'license nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse', 'license practical nurse lpn', 'license pratical nurse', 'license registered nurse', 'license vocatioanl nurse', 'license vocational nurse', 'license vocational nurse', 'license vocational nurse', 'license vocational nurse', 'license vocational nurse', 'licensed nurse', 'licensed nurse', 'licensed nurse', 'licensed nurse', 'licensed nurse', 'licensed nurse', 'licensed nurse', 'licensed nurse', 'licensed nurse', 'licensed nurse', 'licensed nurse', 'licensed nurse assistant', 'licensed nurse assistant', 'licensed nurse/charge nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse', 'licensed practical nurse -lpn', 'licensed practicle nurse', 'licensed pratical nurse', 'licensed pratical nurse', 'licensed pratical nurse', 'licensed prctical nurse', 'licensed vacational nurse', 'licensed vicational nurse', 'licensed vocation nurse', 'licensed vocational nurse', 'licensed vocational nurse', 'licensed vocational nurse', 'licensed vocational nurse', 'licensed vocational nurse', 'licensed

In [192]:
# print(clusters[2])  # other
print(clusters[16]) # business / banker

# print(clusters[0])  # housekeeping
# print(clusters[1])  # parts 
# print(clusters[3])  # service 
# print(clusters[4])  # teacher
# print(clusters[6])  # owner
# print(clusters[7])  # assistant 
# print(clusters[8])  # engineer 
# print(clusters[10]) # consultant
# print(clusters[11]) # secretary
# print(clusters[12]) # analyst
# print(clusters[13]) # driver
# print(clusters[20]) # clerk
# print(clusters[21]) # officer
# print(clusters[23]) # technician
# print(clusters[24]) # specialist
# print(clusters[25]) # team lead 
# print(clusters[27]) # operator
# print(clusters[28]) # president
# print(clusters[29]) # administrator
# print(clusters[30]) # director
# print(clusters[31]) # associate
# print(clusters[33]) # payroll 
# print(clusters[34]) # office 
# print(clusters[36]) # professor
# print(clusters[37]) # attorney
# print(clusters[17]) # coordinator
# print(clusters[18]) # supervisor

# print(clusters[14]) # project manager
# print(clusters[5])  # general manager
# print(clusters[19]) # manager

# print(clusters[15]) # nurse
# print(clusters[32]) # rn

# print(clusters[9])  # marketing 
# print(clusters[22]) # sales

# print(clusters[26]) # executive BUT account
# print(clusters[35]) # accounting

['banker', 'vp business development', 'about business controls manager', 'accountant/business manager', 'ach business analysis manager', 'admin assistant/business manager', 'admissions / business office manager', 'ag and business banker', 'aml business liaison', 'application business engineer', 'area business leader', 'area business manager', 'area business manager', 'area business manager', 'area business manager', 'area business manager', 'area business manager', 'area business manager', 'area business unit manager', 'assistant business counselor', 'assistant business manager', 'assistant business manager', 'assistant business manager', 'assistant business manager', 'assistant business manager', 'assistant business manager', 'assistant business manager', 'assistant business manager', 'assistant business manager', 'assistant director, business development', 'assistant superintendent of business ser', 'assistant superintendent, business svc', 'associte business manager', 'asst director business analysis', 'asst supt business', 'aviation business process manager', 'avp - business analysis manager', 'avp / business development', 'avp / business development officer', 'avp business development', 'avp business rental', 'avp for business', 'avp of business dev. & strategy', 'avp of business development', 'avp personal business banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker - operations vp', 'banker 2', 'banker 4', 'banker  vp', 'banker manager', 'branch banker', 'branch banker', 'branch banker', 'branch banker', 'branch banker', 'branch banker', 'branch banker', 'branch banker', 'branch banker', 'branch banker', 'branch relationship banker', 'business', 'business', 'business  manager', 'business & finance manager', 'business & human resource mgr.', 'business &a planning mgr', 'business acceptance assistant', 'business account manager', 'business account manager', 'business account manager', 'business account representative', 'business accountant i', 'business admin', 'business admin', 'business admin support', 'business administraor', 'business administration', 'business administration', 'business administrstor', 'business advisor', 'business advisor', 'business advisor', 'business advisor', 'business advisor', 'business advisor/trainer', 'business affairs, entertainment', 'business agent', 'business agent', 'business agent', 'business agent', 'business agent', 'business agent', 'business agent', 'business agent', 'business analayst', 'business analst', 'business analsyt', 'business analsyt/tester', 'business analyast', 'business analyist 2', 'business analysis', 'business analysis', 'business analysis', 'business analysis', 'business analysis', 'business analysis', 'business analysis manager', 'business analysis manager', 'business analysis manager', 'business analysis manager', 'business analysis mgr', 'business analysis senior', 'business analysr', 'business analysts', 'business analytics admin', 'business analytics manager', 'business analytics manager', 'business analytics manager', 'business anaylst', 'business anaylst', 'business and operations manager', 'business and sales development', 'business and technology application spec', 'business and training manager', 'business anlayst', 'business anlyst', 'business anslyst', 'business application development manager', 'business application manager', 'business application manager', 'business application manager', 'business applications manager', 'business applications manager', 'business appplication developer', 'business appraiser', 'business architect', 'business architect', 'business architect', 'business archtiect', 'business area lead', 'business area manager', 'business area manager', 'business area manager', 'business assistant', 'business assistant', 'business assistant', 'business assistant', 'business assistant', 'business assistant', 'business assistant', 'business assistant', 'business assistant', 'business assistant', 'business assitant', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker', 'business banker vice president', 'business banking', 'business banking admin', 'business banking admin manager', 'business banking area manager', 'business banking assistant', 'business banking assoicate', 'business banking client service admin', 'business banking manager', 'business banking manager', 'business banking relationship manager', 'business banking relationship manager', 'business banking relationship manager', 'business banking rep.', 'business banking sales assistant ii', 'business banking sales manager', 'business billing advisor', 'business broker', 'business capacity owner', 'business capacity owner', 'business captain', 'business center manager', 'business center manager', 'business center manager', 'business change advisor', 'business change advisor', 'business change manager', 'business class foreman', 'business class tech', 'business client manager', 'business coach', 'business coach', 'business coach', 'business coach', 'business consultan5', 'business consultants', 'business continuity analysts', 'business continuity leader', 'business continuity manager', 'business continuity manager', 'business continuity manager', 'business continuity manager', 'business control manager', 'business control manager', 'business control plan advisor', 'business control specialists', 'business controller', 'business cordinator', 'business credit manager', 'business critical account mgr', 'business delivery driver', 'business dev', 'business dev', 'business dev manager', 'business dev manager', 'business dev rep', 'business deve', 'business devellopment manager', 'business developement', 'business developement', 'business developement manager', 'business developement manager', 'business developement manager', 'business developement manager', 'business developer', 'business developer', 'business developer/vp', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development', 'business development - internet', 'business development - us production', 'business development & government rel.', 'business development & marketing manager', 'business development sales', 'business development administrator', 'business development analyst', 'business development analyst', 'business development analyst', 'business development analyst', 'business development analyst', 'business development analyst', 'business development analyst', 'business development analyst', 'business development analytics - m&a', 'business development and operations mgr', 'business development associate', 'business development associate', 'business development associate', 'business development associate', 'business development associate', 'business development associate', 'business development associate', 'business development asst. manager', 'business development coach', 'business development communications mana', 'business development conferences', 'business development consultant', 'business development consultant', 'business development consultant', 'business development consultant', 'business development consultant', 'business development consultant', 'business development consultant', 'business development coordinator', 'business development coordinator', 'business development coordinator', 'business development coordinator', 'business development coordinator', 'business development coordinator', 'business development coordinator', 'business development coordinator', 'business development coordinator', 'business development coordinator', 'business development coordinator', 'business development data analyst', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director', 'business development director, us', 'business development directot', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive', 'business development executive ii', 'business development lead', 'business development lead', 'business development leader', 'business development managee', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development manager', 'business development 

In [195]:
clusters[16]

['banker',
 'vp business development',
 'about business controls manager',
 'accountant/business manager',
 'ach business analysis manager',
 'admin assistant/business manager',
 'admissions / business office manager',
 'ag and business banker',
 'aml business liaison',
 'application business engineer',
 'area business leader',
 'area business manager',
 'area business manager',
 'area business manager',
 'area business manager',
 'area business manager',
 'area business manager',
 'area business manager',
 'area business unit manager',
 'assistant business counselor',
 'assistant business manager',
 'assistant business manager',
 'assistant business manager',
 'assistant business manager',
 'assistant business manager',
 'assistant business manager',
 'assistant business manager',
 'assistant business manager',
 'assistant business manager',
 'assistant director, business development',
 'assistant superintendent of business ser',
 'assistant superintendent, business svc',
 'associte business manager',
 'asst director business analysis',
 'asst supt business',
 'aviation business process manager',
 'avp - business analysis manager',
 'avp / business development',
 'avp / business development officer',
 'avp business development',
 'avp business rental',
 'avp for business',
 'avp of business dev. & strategy',
 'avp of business development',
 'avp personal business banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker',
 'banker - operations vp',
 'banker 2',
 'banker 4',
 'banker  vp',
 'banker manager',
 'branch banker',
 'branch banker',
 'branch banker',
 'branch banker',
 'branch banker',
 'branch banker',
 'branch banker',
 'branch banker',
 'branch banker',
 'branch banker',
 'branch relationship banker',
 'business',
 'business',
 'business  manager',
 'business & finance manager',
 'business & human resource mgr.',
 'business &a planning mgr',
 'business acceptance assistant',
 'business account manager',
 'business account manager',
 'business account manager',
 'business account representative',
 'business accountant i',
 'business admin',
 'business admin',
 'business admin support',
 'business administraor',
 'business administration',
 'business administration',
 'business administrstor',
 'business advisor',
 'business advisor',
 'business advisor',
 'business advisor',
 'business advisor',
 'business advisor/trainer',
 'business affairs, entertainment',
 'business agent',
 'business agent',
 'business agent',
 'business agent',
 'business agent',
 'business agent',
 'business agent',
 'business agent',
 'business analayst',
 'business analst',
 'business analsyt',
 'business analsyt/tester',
 'business analyast',
 'business analyist 2',
 'business analysis',
 'business analysis',
 'business analysis',
 'business analysis',
 'business analysis',
 'business analysis',
 'business analysis manager',
 'business analysis manager',
 'business analysis manager',
 'business analysis manager',
 'business analysis mgr',
 'business analysis senior',
 'business analysr',
 'business analysts',
 'business analytics admin',
 'business analytics manager',
 'business analytics manager',
 'business analytics manager',
 'business anaylst',
 'business anaylst',
 'business and operations manager',
 'business and sales development',
 'business and technology application spec',
 'business and training manager',
 'business anlayst',
 'business anlyst',
 'business anslyst',
 'business application development manager',
 'business application manager',
 'business application manager',
 'business application manager',
 'business applications manager',
 'business applications manager',
 'business appplication developer',
 'business appraiser',
 'business architect',
 'business architect',
 'business architect',
 'business archtiect',
 'business area lead',
 'business area manager',
 'business area manager',
 'business area manager',
 'business assistant',
 'business assistant',
 'business assistant',
 'business assistant',
 'business assistant',
 'business assistant',
 'business assistant',
 'business assistant',
 'business assistant',
 'business assistant',
 'business assitant',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker',
 'business banker vice president',
 'business banking',
 'business banking admin',
 'business banking admin manager',
 'business banking area manager',
 'business banking assistant',
 'business banking assoicate',
 'business banking client service admin',
 'business banking manager',
 'business banking manager',
 'business banking relationship manager',
 'business banking relationship manager',
 'business banking relationship manager',
 'business banking rep.',
 'business banking sales assistant ii',
 'business banking sales manager',
 'business billing advisor',
 'business broker',
 'business capacity owner',
 'business capacity owner',
 'business captain',
 'business center manager',
 'business center manager',
 'business center manager',
 'business change advisor',
 'business change advisor',
 'business change manager',
 'business class foreman',
 'business class tech',
 'business client manager',
 'business coach',
 'business coach',
 'business coach',
 'business coach',
 'business consultan5',
 'business consultants',
 'business continuity analysts',
 'business continuity leader',
 'business continuity manager',
 'business continuity manager',
 'business continuity manager',
 'business continuity manager',
 'business control manager',
 'business control manager',
 'business control plan advisor',
 'business control specialists',
 'business controller',
 'business cordinator',
 'business credit manager',
 'business critical account mgr',
 'business delivery driver',
 'business dev',
 'business dev',
 'business dev manager',
 'business dev manager',
 'business dev rep',
 'business deve',
 'business devellopment manager',
 'business developement',
 'business developement',
 'business developement manager',
 'business developement manager',
 'business developement manager',
 'business developement manager',
 'business developer',
 'business developer',
 'business developer/vp',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development',
 'business development - internet',
 'business development - us production',
 'business development & government rel.',
 'business development & marketing manager',
 'business development sales',
 'business development administrator',
 'business development analyst',
 'business development analyst',
 'business development analyst',
 'business development analyst',
 'business development analyst',
 'business development analyst',
 'business development analyst',
 'business development analyst',
 'business development analytics - m&a',
 'business development and operations mgr',
 'business development associate',
 'business development associate',
 'business development associate',
 'business development associate',
 'business development associate',
 'business development associate',
 'business development associate',
 'business development asst. manager',
 'business development coach',
 'business development communications mana',
 'business development conferences',
 'business development consultant',
 'business development consultant',
 'business development consultant',
 'business development consultant',
 'business development consultant',
 'business development consultant',
 'business development consultant',
 'business development coordinator',
 'business development coordinator',
 'business development coordinator',
 'business development coordinator',
 'business development coordinator',
 'business development coordinator',
 'business development coordinator',
 'business development coordinator',
 'business development coordinator',
 'business development coordinator',
 'business development coordinator',
 'business development data analyst',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director',
 'business development director, us',
 'business development directot',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive',
 'business development executive ii',
 'business development lead',
 'business development lead',
 'business development leader',
 'business development managee',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',
 'business development manager',

In [176]:
clusters_back = clusters.copy()

In [196]:
# print(clusters[16]) # business / banker

clusters_back[16] = [x for x in clusters[16] if ("bank" not in x)] # business 
clusters_back[39] = [x for x in clusters[16] if ("bank" in x)] # banker

In [177]:
# print(clusters[14]) # project manager
# print(clusters[5])  # general manager
# print(clusters[19]) # manager

managers = clusters_back[14] + clusters_back[5] + clusters_back[19]

clusters_back[5] = managers

clusters_back[14] = []

clusters_back[19] = []

In [178]:
# print(clusters[15]) # nurse
# print(clusters[32]) # rn

nurses = clusters_back[15] + clusters_back[32] 

clusters_back[15] = nurses

clusters_back[32] = []

In [179]:
# print(clusters[9])  # marketing 
# print(clusters[22]) # sales

sales_market = clusters_back[9] + clusters_back[22] 

clusters_back[9] = sales_market

clusters_back[22] = []

In [180]:
# print(clusters[26]) # executive BUT account
# print(clusters[35]) # accounting

accounts = [x for x in clusters_back[26] if ("account" in x)]

clusters_back[35] = accounts + clusters_back[35]

clusters_back[26] = [x for x in clusters_back[26] if ("account" not in x)]

In [167]:
for cluster_label, cluster_titles in dict(sorted(clusters_back.items())).items():
    print(f"Cluster {cluster_label}:")
    print(len(cluster_titles))

Cluster 0:
287
Cluster 1:
701
Cluster 2:
156175
Cluster 3:
6450
Cluster 4:
10820
Cluster 5:
36404
Cluster 6:
7193
Cluster 7:
11121
Cluster 8:
11270
Cluster 9:
13414
Cluster 10:
4551
Cluster 11:
1615
Cluster 12:
11137
Cluster 13:
8610
Cluster 14:
1
Cluster 15:
11985
Cluster 16:
3743
Cluster 17:
6437
Cluster 18:
9890
Cluster 19:
1
Cluster 20:
3363
Cluster 21:
8447
Cluster 22:
1
Cluster 23:
7934
Cluster 24:
10992
Cluster 25:
2643
Cluster 26:
2780
Cluster 27:
5968
Cluster 28:
5574
Cluster 29:
3802
Cluster 30:
12702
Cluster 31:
4962
Cluster 32:
1
Cluster 33:
810
Cluster 34:
4302
Cluster 35:
5487
Cluster 36:
1549
Cluster 37:
2200

In [205]:
# CHECK IF GOOD
summary = 0
for x in clusters_back.values():
    summary += len(x)

print(summary)

395318

In [182]:
new_employee_titles = clusters_back[2]

In [183]:
# Transform titles into TF-IDF features
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(new_employee_titles)

In [184]:
# Apply KMeans clustering
kmeans = KMeans(n_clusters=10, random_state=42, n_init = 'auto')
kmeans.fit(X)

# Get cluster labels
labels = kmeans.labels_

# Create clusters dictionary
new_clusters = {}
for i, title in enumerate(new_employee_titles):
    cluster_label = labels[i]
    if cluster_label not in new_clusters:
        new_clusters[cluster_label] = []
    new_clusters[cluster_label].append(title)

In [187]:
for cluster_label, cluster_titles in dict(sorted(new_clusters.items())).items():
    print(f"Cluster {cluster_label}:")
    print(cluster_titles[0:20])
    print()

Cluster 0:
['administrative.shipping mrg', 'const. mrg.', 'dept mrg', 'gernal mrg', 'logistics mrg', 'mrg documenation control']

Cluster 1:
['admin systems mgr', 'administrative systems mgmr', 'advisor enterprise systems', 'aircraft armament systems', 'aircraft fuel systems', 'airways transportation systems specialis', 'alignment systems manager', 'assistant manager, pharmacy systems supp', 'assoc. info. systems analystspecialist', 'associate information systems anyalst', 'asst direct project information systems', 'at water systems tech', 'av/video systems engineer', 'aviation transportation systems manager', 'avionics systems helper', 'avp clinical information systems', 'avp, systems admin', 'billing systems manager', 'billing systems manager', 'building systems mananger']

Cluster 2:
['membership representative', 'a&d representative', 'a/p representative', 'a/r field representative', 'a/r representative', 'access care representative', 'access point support representative', 'access representative', 'access representative ii', 'account claims representative ii', 'account payables representative', 'accounts payable representative', 'accounts receivable representative', 'accounts representative', 'accouting representative', 'adjustments representative', 'administrative representative', 'admission representative', 'admission representative', 'admissions representative']

Cluster 3:
['ac tech', 'ccht dialsys tech', 'machine tech', 'pharmacy tech', 'sr. facilities tech.', 'tech asst', '#1 rental tech', '1st class lab tech', '214 finishing tech', '2nd tech support agent', '911 user tech', 'a tech', 'a -tech', 'a.i tech', 'a/c tech', 'a/c tech', 'a/c tech', 'a/c tech', 'a/c tech', 'a/c tech']

Cluster 4:
['electronics manager', 'acc manager', 'collection manager', 'division frontend manager', 'food safety & quality manager', 'grocery manager', 'kitchen manager', 'licensed relationship manager', 'manager, clinical data management', 'nanny/ house manager', 'operating manager', 'sr. facilities operations manager', '!st assistant plumbing manager', '0vernite support manager', '1 level manager', '1099 employee- sales manager', '1st assistant floorcoverings manager', '1st asst. manager', '1st level manager', '2nd manager']

Cluster 5:
['area maintenance manager', 'building maintenance tech', 'fac maintenance', 'golf maintenance', 'maintenance', 'maintenance', 'maintenance', 'maintenance-  fabricator', 'maintenance lead', 'maintenance painter', '2 in charge of property maintenance', '339 maintenance', 'a maintenance mechanic', 'ac maintenance', 'age maintenance', 'agm of maintenance', 'aircraft maintenance', 'aircraft maintenance', 'aircraft maintenance', 'aircraft maintenance']

Cluster 6:
['3d designer', 'academic designer', 'academic designer', 'advanced designer', 'advanced senior designer', 'animator/designer', 'app designer', 'apparel designer', 'arch designer', 'architectural designer', 'architectural designer', 'architectural designer', 'architectural designer', 'architectural designer', 'architectural designer', 'architectural designer', 'architectural designer', 'architectural technical designer ii', 'architecture cad designer', 'art designer']

Cluster 7:
['aircraft worker machinist', 'areospace machinist', 'assembler / machinist', 'automotive machinist', 'aviation machinist', 'cnc lead machinist', 'cnc machinist', 'cnc machinist', 'cnc machinist', 'cnc machinist', 'cnc machinist', 'cnc machinist', 'cnc machinist', 'cnc machinist', 'cnc machinist', 'cnc machinist', 'cnc machinist', 'cnc machinist', 'cnc machinist', 'cnc machinist']

Cluster 8:
['day care proivder', 'letter carrier', 'carpenter', 'lead caterer', 'adv mtr proj fld rep', 'admin asst', 'advance cnn', 'afjrotc teacher', 'aftermarket expeditor', 'agent staff', 'ambulatory rn clinic supervisor', 'and planned director of major gifts', 'apprentice', 'architect', 'assembler', 'assembler', 'auditor', 'auto mechanic', 'avp, private client support', 'baker']

Cluster 9:
['founder & principal / senior researcher', 'senior ce', 'accountant senior', 'administrative senior pastor', 'administrative support senior', 'advisory senior manager', 'aircraft mechanic senior', 'applecare senior advisor', 'assembler senior', 'assistant vp, senior technology developr', 'assurance senior', 'assurance senior', 'assurance senior', 'assurance senior manager', 'assurance senior manager', 'assurance services senior', 'audio visual senior acct. manager', 'audit senior', 'audit senior', 'audit senior']

In [189]:
for cluster_label, cluster_titles in dict(sorted(new_clusters.items())).items():
    print(f"Cluster {cluster_label}:")
    print(len(cluster_titles))

Cluster 0:
6
Cluster 1:
503
Cluster 2:
1793
Cluster 3:
5542
Cluster 4:
12081
Cluster 5:
1802
Cluster 6:
1596
Cluster 7:
877
Cluster 8:
128176
Cluster 9:
3799

In [144]:
# print(new_clusters[0]) # other
# print(new_clusters[1]) # systems
# print(new_clusters[2]) # representative
# print(new_clusters[3]) # tech
# print(new_clusters[4]) # manager
# print(new_clusters[5]) # maintenance 
# print(new_clusters[6]) # designer
# print(new_clusters[7]) # machinist
# print(new_clusters[8]) # other
# print(new_clusters[9]) # other

['founder & principal / senior researcher', 'senior ce', 'accountant senior', 'administrative senior pastor', 'administrative support senior', 'advisory senior manager', 'aircraft mechanic senior', 'applecare senior advisor', 'assembler senior', 'assistant vp, senior technology developr', 'assurance senior', 'assurance senior', 'assurance senior', 'assurance senior manager', 'assurance senior manager', 'assurance services senior', 'audio visual senior acct. manager', 'audit senior', 'audit senior', 'audit senior', 'audit senior', 'audit senior', 'audit senior', 'audit senior', 'audit senior', 'audit senior manager', 'audit senior manager', 'audit senior manager', 'avionics installer senior', 'avp -senior field examiner', 'avp senior underwritier', 'avp, senior auditor 1', 'avp; senior investigator', 'bank officer senior customer care spec.', 'battalion senior medic', 'bbt senior', 'bio med senior', 'bn senior medic', 'branch senior', 'casesmart senior flex developer', 'cc senior manager', 'ccp senior', 'cerpf senior operations nco', 'civilian senior scientist', 'clerical, senior', 'communications tech, senior', 'corporate senior buyer', 'counsel to the president and senior advo', 'cpa - senior accountant', 'cpa - tax compliance senior', 'cpi billing services senior', 'critical care senior staff nurse', 'csr senior transportation', 'ct tech senior', 'default risk assistant senior', 'delegated senior auditor', 'dentist senior scientific researcher', 'desktop support senior', 'developer senior work at home employee', 'digital transformation senior manager', 'director - senior citizen center', 'domestic senior service worker', 'e discovery senior manager', 'e-8, senior master sergeant', 'enterprise architect, senior', 'enterprise tech support senior advisor', 'evp senior lender', 'executive senior vacation planner', 'financial advisor/senior vice pres', 'founder & senior principal', 'global senior brand manager', 'global senior logistics manager', 'global tax & legal senior talent advisor', 'heavy senior mechanic', 'home equity senior underwriter', 'hr generalist, senior', 'hr recruiting senior manager', 'infrastructure senior principal', 'ios senior advisor', 'it - senior desktop suppot tech.', 'it applications programmer senior', 'it field services tech, senior', 'it senior', 'it senior application developer', 'it senior archetect', 'it senior lead', 'it senior programmer', 'it support tech senior', 'it tech serv senior', 'lead/senior technologist', 'legal - senior regulatory counsel', 'library senior page', 'loan servicing senior', 'manager/senior scientist', 'market intelligence senior manager', 'mutual funds senior associate', 'network security senior advisor', 'northeast senior sales executive', 'on premise senior sales relief', 'ourside senior sales engineer', 'p and r senior teller', 'pmo senior manager', 'portables senior account manager', 'prepaid senior product manager', 'principle senior security architect', 'pro support senior technical advisor', 'product delivery senior manager', 'product development/senior tech', 'production senior lead and cnc programme', 'production senior lead and cnc programme', 'professional applications senior advisor', 'program lead, senior', 'program planner senior', 'program planner senior', 'programmer senior', 'project manager / senior system architec', 'prototype procurement senior', 'qa senior manager', 'r.n. - senior clinical liaison', 'recreation leader-senior fitness', 'refuse collector senior', 'regional vp-senior applications mngr', 'relationship manager senior vp', 'relocation senior', 'research nurse senior', 'research senior searcher', 'rrt, senior lead', 'sales capture - senior manager', 'senior', 'senior', 'senior', 'senior', 'senior', 'senior', 'senior', 'senior', 'senior', 'senior', 'senior', 'senior', 'senior', 'senior  accountant', 'senior  broker', 'senior  commercial underwriting counsel', 'senior  developer', 'senior  relationship manager', 'senior - tech support', 'senior 3d artist', 'senior 3d visualizer', 'senior aba therpaist', 'senior abstractor', 'senior abstractor', 'senior academic counselor', 'senior academic counselor', 'senior academic generalist', 'senior academic researcher', 'senior accounant', 'senior account adm.', 'senior account clsims rep', 'senior account excutive', 'senior account manager - immunotherapy', 'senior account mngr', 'senior accountand', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant', 'senior accountant lead', 'senior accountant 4', 'senior accountant auditor', 'senior accountant ii', 'senior accountant ii', 'senior accountant, ap&purchasing manager', 'senior accountant, cpa', 'senior accountant/cpa', 'senior accountant-caterpillar financial', 'senior accountent', 'senior accountnant', 'senior accounts payable accountant', 'senior accounts payable processor', 'senior accounts receivable', 'senior accoutning tech', 'senior accpuntant', 'senior acct manager', 'senior acct manager', 'senior acct mgr', 'senior acct mgr', 'senior acctng', 'senior acoount manager', 'senior acountant', 'senior acquisitions editor', 'senior acquisitions editor', 'senior acquisitions manager', 'senior active directory admin', 'senior add ass', 'senior adjuster', 'senior adjuster', 'senior adjuster', 'senior adjuster', 'senior adjuster', 'senior adjuster', 'senior admin', 'senior admin', 'senior admin', 'senior admin', 'senior admin', 'senior admin', 'senior admin', 'senior admin', 'senior admin asst', 'senior administration', 'senior administration', 'senior administrative', 'senior administrative', 'senior administrative assisant', 'senior administrative support', 'senior adminstrator', 'senior admissions advisoe', 'senior admissions advisor', 'senior admissions advisor', 'senior admissions rep', 'senior adops manager', 'senior adviser', 'senior adviser of information magmt', 'senior adviso', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor', 'senior advisor architecture', 'senior advisor for strategic communicati', 'senior advisor t-2 apple', 'senior advisory', 'senior advocacy counselor', 'senior advocate', 'senior agent', 'senior agent', 'senior agent', 'senior agent', 'senior agent', 'senior agent', 'senior agent', 'senior agent', 'senior agent', 'senior agent', 'senior aide to the mayor', 'senior air safety investigator', 'senior aircraft inspector', 'senior aircraft mechanic', 'senior aircraft tech', 'senior airman', 'senior airman', 'senior airman', 'senior airman', 'senior airman', 'senior airman', 'senior analyist', 'senior analys', 'senior analysis', 'senior analyst concession programs', 'senior analyst pwb design', 'senior analyst-transfer of assets', 'senior analytic scientist', 'senior anaylst', 'senior animator', 'senior animator', 'senior anlayst', 'senior annalyst', 'senior ap investigator', 'senior application analist', 'senior application developer', 'senior application developer', 'senior application developer', 'senior application developer', 'senior application developer', 'senior application developer', 'senior application developer', 'senior application developer', 'senior application developer', 'senior application developer', 'senior application developer', 'senior application developer', 'senior application developer', 'senior application developer', 'senior application developer', 'senior application developer', 'senior application developer', 'senior applications chemist', 'senior applications developer', 'senior applications developer', 'senior applications developer', 'senior applied mechanics engineer', 'senior appraiser', 'senior appraiser', 'senior appraiser', 'senior appraiser', 'senior appraiser', 'senior appraiser', 'senior appraiser', 'senior appraiser', 'senior archaeologist', 'senior archibus developer', 'senior architect', 'senior architect', 'senior architect', 'senior architect', 'senior architect', 'senior architect', 'senior architect', 'senior architect', 'senior architect', 'senior architect', 'senior architect', 'senior architect', 'senior architect', 'senior architect', 'senior architect', 'senior architect', 'senior architect', 'senior architecture managet', 'senior army instructor', 'senior army instructor', 'senior army instructor', 'senior army instructor', 'senior arrow developer', 'senior art manager', 'senior artist', 'senior asociate', 'senior asscoiate', 'senior assembler', 'senior assembler', 'senior assembler', 'senior assembler', 'senior assembler', 'senior assembler', 'senior assembler', 'senior assembly manager', 'senior asset manager', 'senior asset manager', 'senior asset manager', 'senior asset manager', 'senior asset manager', 'senior asset manger', 'senior assisant', 'senior assistant public defender', 'senior assoc 2', 'senior assoc broker', 'senior assocaite', 'senior association', 'senior assoicate', 'senior asst nanager', 'senior assy.', 'senior audit accountant', 'senior audit accountant', 'senior audit manager', 'senior audit manager', 'senior audit manager', 'senior audit manager', 'senior audito', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor', 'senior auditor appraiser', 'senior auditor- sox compliance', 'senior auditor/accountant', 'senior auditot', 'senior auto dispatcher', 'senior auto tech', 'senior automation and electrical special', 'senior automation engineer1', 'senior automotive technucian', 'senior av tech.', 'senior b.i. architect', 'senior ba', 'senior ba', 'senior background investigator', 'senior bailiff', 'senior bank examiner', 'senior bank manager', 'senior bank manager', 'senior bank vault teller', 'senior banquet manager', 'senior banquet manager', 'senior bartender', 'senior beauty advisor', 'senior beauty advisor', 'senior beauty advisor', 'senior behavioral health coach', 'senior behavioral scientist', 'senior benefit adjustor', 'senior beta manager', 'senior biller', 'senior biochemist', 'senior biologist', 'senior bldng inspector', 'senior bnefit counselor', 'senior boa', 'senior board counsel', 'senior body mechanic', 'senior bodyman', 'sen

In [190]:
clusters_back[5] = clusters_back[5] + new_clusters[4] # manager
clusters_back[23] = clusters_back[23] + new_clusters[3] # tech
clusters_back[14] = new_clusters[1] # systems
clusters_back[19] = new_clusters[2] # representative
clusters_back[22] = new_clusters[5] # maintenance
clusters_back[32] = new_clusters[6] # designer
clusters_back[38] = new_clusters[7] # machinist

clusters_back[2] = new_clusters[0] + new_clusters[8] + new_clusters[9] # other

In [197]:
for cluster_label, cluster_titles in dict(sorted(clusters_back.items())).items():
    print(f"Cluster {cluster_label}:")
    print(len(cluster_titles))

Cluster 0:
287
Cluster 1:
701
Cluster 2:
131981
Cluster 3:
6450
Cluster 4:
10820
Cluster 5:
48485
Cluster 6:
7193
Cluster 7:
11121
Cluster 8:
11270
Cluster 9:
13414
Cluster 10:
4551
Cluster 11:
1615
Cluster 12:
11137
Cluster 13:
8610
Cluster 14:
503
Cluster 15:
11985
Cluster 16:
2452
Cluster 17:
6437
Cluster 18:
9890
Cluster 19:
1793
Cluster 20:
3363
Cluster 21:
8447
Cluster 22:
1802
Cluster 23:
13476
Cluster 24:
10992
Cluster 25:
2643
Cluster 26:
2780
Cluster 27:
5968
Cluster 28:
5574
Cluster 29:
3802
Cluster 30:
12702
Cluster 31:
4962
Cluster 32:
1596
Cluster 33:
810
Cluster 34:
4302
Cluster 35:
5487
Cluster 36:
1549
Cluster 37:
2200
Cluster 38:
877
Cluster 39:
1291

In [198]:
final_clusters = dict()

In [ ]:
# print(clusters[2])  # other
# print(clusters[16]) # business / banker

# print(clusters[0])  # housekeeping
# print(clusters[1])  # parts 
# print(clusters[3])  # service 
# print(clusters[4])  # teacher
# print(clusters[6])  # owner
# print(clusters[7])  # assistant 
# print(clusters[8])  # engineer 
# print(clusters[10]) # consultant
# print(clusters[11]) # secretary
# print(clusters[12]) # analyst
# print(clusters[13]) # driver
# print(clusters[20]) # clerk
# print(clusters[21]) # officer
# print(clusters[23]) # technician
# print(clusters[24]) # specialist
# print(clusters[25]) # team lead 
# print(clusters[27]) # operator
# print(clusters[28]) # president
# print(clusters[29]) # administrator
# print(clusters[30]) # director
# print(clusters[31]) # associate
# print(clusters[33]) # payroll 
# print(clusters[34]) # office 
# print(clusters[36]) # professor
# print(clusters[37]) # attorney
# print(clusters[17]) # coordinator
# print(clusters[18]) # supervisor

# print(clusters[14]) # project manager
# print(clusters[5])  # general manager
# print(clusters[19]) # manager

# print(clusters[15]) # nurse
# print(clusters[32]) # rn

# print(clusters[9])  # marketing 
# print(clusters[22]) # sales

# print(clusters[26]) # executive BUT account
# print(clusters[35]) # accounting

In [242]:
print(clusters_back[39][0:20])

['banker', 'ag and business banker', 'avp personal business banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker', 'banker']

In [243]:
final_clusters["housekeeping"] = clusters_back[0]
final_clusters["parts"] = clusters_back[1]
final_clusters["other"] = clusters_back[2]
final_clusters["service"] = clusters_back[3]
final_clusters["teacher"] = clusters_back[4]
final_clusters["manager"] = clusters_back[5]
final_clusters["owner"] = clusters_back[6]
final_clusters["assistant"] = clusters_back[7]
final_clusters["engineer"] = clusters_back[8]
final_clusters["marketing and sales"] = clusters_back[9]
final_clusters["consultant"] = clusters_back[10]
final_clusters["secretary"] = clusters_back[11]
final_clusters["analyst"] = clusters_back[12]
final_clusters["driver"] = clusters_back[13]
final_clusters["systems "] = clusters_back[14]
final_clusters["nurse"] = clusters_back[15]
final_clusters["business"] = clusters_back[16]
final_clusters["coordinator"] = clusters_back[17]
final_clusters["supervisor"] = clusters_back[18]
final_clusters["representative"] = clusters_back[19]
final_clusters["clerk"] = clusters_back[20]
final_clusters["officer"] = clusters_back[21]
final_clusters["maintenance"] = clusters_back[22]
final_clusters["technician"] = clusters_back[23]
final_clusters["specialist"] = clusters_back[24]
final_clusters["leader"] = clusters_back[25]
final_clusters["executive"] = clusters_back[26]
final_clusters["operator"] = clusters_back[27]
final_clusters["president"] = clusters_back[28]
final_clusters["administrator"] = clusters_back[29]
final_clusters["director"] = clusters_back[30]
final_clusters["associate"] = clusters_back[31]
final_clusters["designer"] = clusters_back[32]
final_clusters["payroll"] = clusters_back[33]
final_clusters["office"] = clusters_back[34]
final_clusters["account"] = clusters_back[35]
final_clusters["professor"] = clusters_back[36]
final_clusters["attorney"] = clusters_back[37]
final_clusters["machinist"] = clusters_back[38]
final_clusters["banker"] = clusters_back[39]

In [244]:
# CHECK IF GOOD
summary = 0
for x in final_clusters.values():
    summary += len(x)

print(summary)

395318

In [251]:
final_clusters_df = pd.DataFrame.from_dict(final_clusters, orient='index').transpose()

In [252]:
final_clusters_df.to_excel("titles_clusters.xlsx")

---

In [2]:
import pandas as pd

In [5]:
employee_dictionary = pd.read_excel("titles_clusters_good.xlsx")

In [25]:
dataset = pd.read_excel("predicted_data_accepted_new.xlsx")

In [14]:
employee_dictionary = employee_dictionary.iloc[:,1:]

In [18]:
employee_dictionary.drop("other", axis = 1, inplace=True)

In [22]:
employee_dictionary.transpose()

,index,0,1,2,3,4,5,6,7,8,...,132088,132089,132090,132091,132092,132093,132094,132095,132096,132097
0,housekeeping,housekeeping,account manager for housekeeping,assistant director for housekeeping serv,assistant director housekeeping,assistant director of housekeeping,assistant director of housekeeping,assistant director of housekeeping,assistant director of housekeeping,assistant housekeeping manager,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,parts,parts manager,aftermarket parts project manager,air craft parts mechanic,aircraft parts clerk,aircraft parts repairer,assistant parts manager,assistant parts manager,assistant parts manager,assistant parts manager,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,service,customer service representative,dining service,public service supervisor,service deli,service provider,a/c service tech,access service rep,account service,account service manager,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,teacher,assistant teacher,teacher,teacher,teacher,teacher,teacher,teacher assistant,a teacher,a.teacher,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,manager,cyber project manager,project director,project manager,account/ project manager,account/project manager,administration/project manager,administrative project manager,agile project manager,agronomy project manager,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,owner,co-owner,`owner/mechanic,"a member, owner",accountant - owner,accountant/owner,advisor/owner,agent - owner,agent - owner,agent owner,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,assistant,assistant store manager,administration assistant,assistant branch manager,assistant butler,assistant manager,assistant principal,assistant store manager,assistant store manager in training,lab assistant,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,engineer,building engineer,1st engineer,2 nd engineer,2nd assistant engineer,2nd engineer,2nd engineer,911 engineer,a/v engineer,access management engineer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,marketing and sales,event marketing manager,marketing manager,regional marketing coordinator,academic marketing,accounts manager / marketing,activity/marketing director,ad marketing,ad marketing,ad sales marketing manager,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,consultant,consultant,consultant,leasing & sales consultant,401k education consultant,academic consultant,account consultant,account consultant,account consultant,account consultant,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,secretary,1446 secretary,accounting department secretary,adm secretary,adm. secretary,admin school secretary,admin secretary,admin secretary,admin secretary,admin secretary,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,analyst,business analyst,derivative analyst,financial analyst,financial analyst,senior supply analyst,sr. analyst,2 level it analyst,a/p analyst,a/r analyst,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,driver,commercial driver,driver,driver,driver,driver,driver,driver,fork truck driver,truck driver,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,systems,admin systems mgr,administrative systems mgmr,advisor enterprise systems,aircraft armament systems,aircraft fuel systems,airways transportation systems specialis,alignment systems manager,"assistant manager, pharmacy systems supp",assoc. info. systems analystspecialist,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,nurse,nurse practitioner,registered nurse,registered nurse,registered nurse,registered nurse,registered nurse,school nurse,administrative nurse,administrative nurse,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,business,vp business development,about business controls manager,accountant/business manager,ach business analysis manager,admin assistant/business manager,admissions / business office manager,aml business liaison,application business engineer,area business leader,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,coordinator,appraisal coordinator,coordinator,coordinator,rental coordinator,340-b coordinator,a.t coordinator,a/p a/r coordinator,a/p coordinator,a/p coordinator,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,supervisor,kitchen supervisor,lab supervisor,or supervisor,qa supervisor,satellite supervisor,stock supervisor,supervisor,supervisor,supervisor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,representative,membership representative,a&d representative,a/p representative,a/r field representative,a/r representative,access care representative,access point support representative,access representative,access representative ii,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,clerk,copy clerk,inventory clerk,shipping receiving clerk,1408-principal clerk,a/p clerk,a/p clerk,a/r - a/p clerk,a/r clerk,a/r clerk,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,officer,compliance officer,l corrections officer,loan officer,loan officer,peace officer,911 training officer,ac officer,access officer,account security officer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,maintenance,area maintenance manager,building maintenance tech,fac maintenance,golf maintenance,maintenance,maintenance,maintenance,maintenance- fabricator,maintenance lead,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,technician,automotive technician,bus technician,certified pharmacy technician,field service technician,instrument and control technician,maintenance technician,office technician,technician,technician,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,specialist,behavior specialist,card services specialist,child protective specialist,compliance specialist,distribution specialist,employment specialist,itoperations specialist,legal office specialist,medical credentialing specialist,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,leader,area leader,cash management team leader,crew leader,team leader supervisor,team leader / driver examiner,2nd shift order fulfillment team lead,2nd shift team lead,3d geohazards team leader,3d project leader,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,executive,executive assistant of sales,acct executive,acct executive,acct executive,acct executive,administrative executive,administrative executive,advertising executive,advertising executive,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,operator,elevator clearance operator,driver/ operator,equipment operator,forklift operator,machine operator,machine operator,machine operator,machine operator,machine operator,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,president,assistant vice president,president,vice president,vice president of sales,vice president relationship manager,1st vice president,1st vice president,1st vice president,1st vice president/financial operations,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,administrator,correctional services administrator,engineering administrator,subcontract administrator,wing administrator,401k administrator,a/p & a/r administrator,a/p administrator,a/r and a/p administrator,academic administrator,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,director,director,assitant director,asst. director of support services,asst. site director,director of institutional research,director of operations,director of production and development,it director,911 director,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,associate,3rd key sales associate,401k plan sales associate,529 senior associate,529 senior associate,a/p associate,a/p associate 3,ab associate,academic associate,academic department associate,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,designer,3d designer,academic designer,academic designer,advanced designer,advanced senior designer,animator/designer,app designer,apparel designer,arch designer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,payroll,payroll supervisor,a/p payroll supervisor,a/p supervisor/payroll admin,accounting & payroll clerk,accounting payroll,accounting specialist payroll,accounting specialist/ payroll,accounting/payroll,accounting/payroll,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,office,office specialist,account manager/office manager,account/office manager,accountant/office manager,accountant/office manager,accountant/office manager,accounts payable/office manager,admin assistant / office manager,admin asst office manager,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,account,capital account manager,academic account manager,account,account,account,account,account,account,account,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,professor,associate professor,academic counselor / professor,adj assistant professor,adjuct professor,adjunct assistant professor,adjunct assistant professor,adjunct assistant professor,adjunct assistant professor,"adjunct assistant professor, psychology",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,attorney,administrative attorney,agency attorney,agency attorney,agency attorney,agency attorney,assisstant attorney general,assistant attorney,assistant attorney general,assistant attorney general,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,machinist,aircraft worker machinist,areospace machinist,assembler / machinist,automotive machinist,aviation machinist,cnc lead machinist,cnc machinist,cnc machinist,cnc machinist,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,banker,banker,ag and business banker,avp personal business banker,banker,banker,banker,banker,banker,banker,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
def cleaning (x : str) -> str:
    if x:
        return (str(x).lower()
                    .replace("(","").replace(")","")
                    .replace(" 0 ","").replace(" 1 ","")
                    .replace(" 2 ","").replace(" 3 ","")
                    .replace(" 4 ","").replace(" 5 ","")
                    .replace(" 6 ","").replace(" 7 ","")
                    .replace(" 8 ","").replace(" 9 ","")
                    .replace('"',"").replace("'","")
                    .replace("V","").replace("I","")
                    .replace("lll","").replace("iii","")
                    .replace(" iv ","").replace("â€‹","")
                    .strip())
    return None

In [49]:
dataset.iloc[19,:]

Unnamed: 0                                19
funded_amnt                            10000
term                               36 months
grade                                      5
emp_title                Contract Specialist
emp_length                               4.0
home_ownership                      MORTGAGE
annual_inc                           91392.0
loan_status                       Fully Paid
purpose                                house
zip_code                               644xx
addr_state                          Missouri
dti                                     9.44
delinq_2yrs                                0
fico_range_low                           710
predicted_loan_status             Fully Paid
emp_cluster                              NaN
Name: 19, dtype: object

In [70]:
clear_clusters = dict()

In [71]:
for clust in employee_dictionary.columns:
    clear_clusters[clust] = employee_dictionary[clust].value_counts().index

In [88]:
for x,li in clear_clusters.items():
    print(x + ":")
    print(len(li))

housekeeping:
64
parts:
215
service:
1370
teacher:
75
manager:
8481
owner:
318
assistant:
2061
engineer:
2001
marketing and sales:
1696
consultant:
1267
secretary:
245
analyst:
2880
driver:
480
systems :
349
nurse:
472
business:
860
coordinator:
2728
supervisor:
1478
representative:
719
clerk:
1018
officer:
1493
maintenance:
431
technician:
4227
specialist:
4954
leader:
1096
executive:
308
operator:
1365
president:
813
administrator:
982
director:
4088
associate:
1618
designer:
427
payroll:
276
office:
412
account:
821
professor:
209
attorney:
189
machinist:
92
banker:
122

In [50]:
employee_dictionary.drop_duplicates()

,housekeeping,parts,service,teacher,manager,owner,assistant,engineer,marketing and sales,consultant,...,director,associate,designer,payroll,office,account,professor,attorney,machinist,banker
0,housekeeping,parts manager,customer service representative,assistant teacher,cyber project manager,co-owner,assistant store manager,building engineer,event marketing manager,consultant,...,director,3rd key sales associate,3d designer,payroll supervisor,office specialist,capital account manager,associate professor,administrative attorney,aircraft worker machinist,banker
1,account manager for housekeeping,aftermarket parts project manager,dining service,teacher,project director,`owner/mechanic,administration assistant,1st engineer,marketing manager,consultant,...,assitant director,401k plan sales associate,academic designer,a/p payroll supervisor,account manager/office manager,academic account manager,academic counselor / professor,agency attorney,areospace machinist,ag and business banker
2,assistant director for housekeeping serv,air craft parts mechanic,public service supervisor,teacher,project manager,"a member, owner",assistant branch manager,2 nd engineer,regional marketing coordinator,leasing & sales consultant,...,asst. director of support services,529 senior associate,academic designer,a/p supervisor/payroll admin,account/office manager,account,adj assistant professor,agency attorney,assembler / machinist,avp personal business banker
3,assistant director housekeeping,aircraft parts clerk,service deli,teacher,account/ project manager,accountant - owner,assistant butler,2nd assistant engineer,academic marketing,401k education consultant,...,asst. site director,529 senior associate,advanced designer,accounting & payroll clerk,accountant/office manager,account,adjuct professor,agency attorney,automotive machinist,banker
4,assistant director of housekeeping,aircraft parts repairer,service provider,teacher,account/project manager,accountant/owner,assistant manager,2nd engineer,accounts manager / marketing,academic consultant,...,director of institutional research,a/p associate,advanced senior designer,accounting payroll,accountant/office manager,account,adjunct assistant professor,agency attorney,aviation machinist,banker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132094,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
mapper = dict()

In [93]:
for k, v_li in clear_clusters.items():
    for v in v_li:
        mapper[v] = k

In [96]:
dataset["emp_cluster"] = (
    dataset["emp_title"]
    .copy()
    .apply(lambda x: cleaning(x) if x else pd.NA)
    .map(mapper)
    .astype("str", errors = 'ignore')
)

In [97]:
dataset.isna().sum()

Unnamed: 0                   0
funded_amnt                  0
term                         0
grade                        0
emp_title                23833
emp_length               23779
home_ownership               0
annual_inc                   0
loan_status                  0
purpose                      0
zip_code                     0
addr_state                   0
dti                          0
delinq_2yrs                  0
fico_range_low               0
predicted_loan_status        0
emp_cluster                  0
dtype: int64

In [101]:
dataset = dataset.iloc[:,1:]

In [103]:
dataset["emp_cluster"].value_counts()

emp_cluster
nan                    155904
manager                 48520
technician              13473
marketing and sales     13413
director                12699
nurse                   11985
engineer                11268
analyst                 11137
assistant               11118
specialist              10991
teacher                 10818
supervisor               9890
driver                   8609
officer                  8447
owner                    7193
service                  6450
coordinator              6436
operator                 5968
president                5574
account                  5486
associate                4961
consultant               4551
office                   4298
administrator            3801
clerk                    3360
executive                2780
leader                   2487
business                 2452
attorney                 2200
maintenance              1802
representative           1792
secretary                1614
designer                 1596
professor                1549
banker                   1291
machinist                 877
payroll                   810
parts                     701
systems                   503
housekeeping              287
Name: count, dtype: int64

In [105]:
dataset.to_excel("predicted_data_accepted_new_full.xlsx")